<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Yuliana" failures="1" tests="2" name="LoginHappyPathTests.java" time="9.719" errors="0" timestamp="2025-06-28T18:46:36 EEST">
  <testcase classname="org.yulianakoprinkova.LoginTests.LoginHappyPathTests" name="verifyTheUserCanLogin" time="2.604"/>
  <testcase classname="org.yulianakoprinkova.LoginTests.LoginHappyPathTests" name="verifyUserCanLogout" time="2.141">
    <failure type="java.lang.AssertionError" message="expected [Successful logout!] but found [Successful logout!
Successful login!]">
      <![CDATA[java.lang.AssertionError: expected [Successful logout!] but found [Successful logout!
Successful login!]
at org.yulianakoprinkova.LoginTests.LoginHappyPathTests.verifyUserCanLogout(LoginHappyPathTests.java:105)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- verifyUserCanLogout -->
</testsuite> <!-- LoginHappyPathTests.java -->
